### PR TITLE
Feature/improve actions

### PR DESCRIPTION
**Pull request by simonschuhmacher**
- Move individual tasks to distinct files
- Add support for deploying to production environment if a tag is pushed
- Do k8s deployment with Helm directly via run command, instead of using task

### CODE REVIEW

**Comment by simonschuhmacher** [comment]
I might change some things again, thus converted it to draft.

**Comment by simonschuhmacher** [comment]
Now ready for your review, @triumphvalley 😋😎

**Review by triumphvalley — APPROVED** [review]
very good boi

**Review by triumphvalley — APPROVED** [review]
wahnsinn

**Pull request merged**
