### PR TITLE
Feature/sonarcube

### LINKED ISSUE #12: Setup SonarCube

### PR DESCRIPTION
**Pull request by Utschu**
## Summary

- Starts a workflow to check code quality
- Sonar Scan is integrated with Gradle
- Add to existing Build & Test tasks such that it runs on every Push together with tests
- Fix a warning shown when running tests due to db closing too early

## Related Issues

- Closes #12 

## Definition of Done

- User story
  - [X] All stated conditions fulfilled
- Code
  - [X] No more code needed
  - [X] No known bugs
- Clean Code
  - [x] JavaDoc has been added
  - [x] API documentation has been added via annotations (if applicable)
  - [x] No unavoidable code smells
- Testing
  - [x] All existing tests pass
  - [x] New unit tests created according to [CONTRIBUTING.md](./CONTRIBUTING.md#-testing-strategy)
  - [x] New unit tests pass
- SonarCloud
  - [x] Quality gate passed
- Compatibility to frontend
  - [x] Compatibility to staging-frontend verified (running frontend locally in Docker container with image matching the deployed image on staging)

### CODE REVIEW

**Comment by simonschuhmacher** [comment]
Thanks for your PR 🙂
I have integrated the scan with the existing build tasks, such that it runs together with the buil & test task, and I integrated it with Gradle, as this is the recommended way to do a sonar scan on Java Gradle projects.

**Comment by simonschuhmacher** [comment]
@triumphvalley 
Added code coverage scan using `jacoco`. 
Note that coverage information is only shown when new code is actually added, as scan is always just depending on diff to main.

I tested it with a new class that had no coverage and it seemed to work just fine (see screenshot)
Bildschirmfoto 2022-04-14 um 11 08 22

**Comment by simonschuhmacher** [comment]
Ready for your review @triumphvalley 🙂

**Review by triumphvalley — APPROVED** [review]
noice

**Review by triumphvalley — APPROVED** [review]

**Review by triumphvalley — APPROVED** [review]
perfect

**Pull request merged**
