### PR TITLE
Make googleCalendarId settable setting sauna props

### LINKED ISSUE #59: Create Google Calendar Event on new Booking
# Summary

When a new booking is made, an event in the Google Calendar, belonging to the sauna that is being booked, should be created for the time at which the booking happens. For that, each sauna needs to have a Google Calendar that belongs to the specific sauna and is read and writeable by the backend.

# Conditions

- [x] Event is created when new booking is made
- [x] ID of the event is stored to the booking, such that the event can be referenced / updated from the backend for future updates
- [x] Event is updated when booking is confirmed
- [x] Add field for Google Calendar ID to each sauna
- [x] Insert events in the Google Calendar with the ID specified for the sauna for which the booking is made
- [x] Add Id to Saunadetails

### PR DESCRIPTION
**Pull request by simonschuhmacher**
## Summary

- Allows to set `googleCalendarId` of a sauna for `POST` and `PUT` requests.
- Fixes wash service being added to price even if disabled

## Related Issues

- Fixes #59 

## Definition of Done

- User story
  - [x] All stated conditions fulfilled
- Code
  - [x] No more code needed
  - [x] No known bugs
- Clean Code
  - [x] JavaDoc has been added
  - [x] API documentation has been added via annotations (if applicable)
  - [x] No unavoidable code smells
- Testing
  - [x] All existing tests pass
  - [x] New unit tests created according to [CONTRIBUTING.md](./CONTRIBUTING.md#-testing-strategy)
  - [x] New unit tests pass
- SonarCloud
  - [x] Quality gate passed
- Compatibility to frontend
  - [x] Compatibility to staging-frontend verified (running frontend locally in Docker container with image matching the deployed image on staging)

### CODE REVIEW

**Comment by triumphvalley** [comment]
@cabernin could you take a look at this, I have no idea 😄

**Review by ghost — DISMISSED** [review]
👍

**Comment by simonschuhmacher** [comment]
I made some changes such that a booking can also be made if google calendar ID is not available for a sauna, so the calendar entry will just not be added in that case.
Could you please review again, @cabernin ? Thx

**Review by ghost — DISMISSED** [review]
nice sieht gut aus

**Review by ghost — APPROVED** [review]

**Pull request merged**
